name: 'XSS Scan with Dalfox'
description: 'XSS Scanning the web application with the Dalfox'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  mode:
    description: 'Scanning Mode ( url / file / pipe / sxss )'
    required: true
  urls:
    description: 'List of multiple urls'
    required: true
  cmd_options:
    description: 'Additional command line options'
    required: false
outputs:
  RESULT: 
    description: 'Scan Result'    
runs:
  using: "composite"
  steps:
    - run: |
        GO111MODULE=on go get github.com/hahwul/dalfox/v2
        GO111MODULE=on go get -u github.com/tomnomnom/qsreplace
        cat ${{ inputs.urls }} | grep "?" | /home/runner/go/bin/qsreplace -a | /home/runner/go/bin/dalfox ${{ inputs.mode }} --silence ${{ inputs.cmd_options}}
      shell: bash
